# Development environment configuration
environment: development

logging:
  level: DEBUG
  format: "%(asctime)s %(name)s %(levelname)s %(message)s"

api:
  host: 0.0.0.0
  port: 8000

# Database: Optional for persistent storage (uncomment if using Postgres)
# database:
#   host: localhost
#   port: 5432
#   name: logging
#   user: postgres  # Add your username
#   password: your_dev_password  # Use .env for security

redis:
  host: localhost  # Or 'redis' in Docker network
  port: 6379

security:
  key: dev secret key  # For testing; override with env in prod

checkpoint_interval_seconds: 60  # Frequent checkpoints for dev