# Production environment configuration
environment: production
debug: false
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
api:
  host: 0.0.0.0
  port: 8000
database:
  uri: ${POSTGRES_URI}  # Use env var for security
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
security:
  api_key: ${API_KEY}  # Must be set via env var
checkpoint:
  interval_seconds: 300  # Less frequent in prod for performance